import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import db from "@/lib/supabase/db";
import { ThemeProvider } from "@/lib/providers/next-theme-provider";
import { twMerge } from "tailwind-merge";
import { Toaster } from "@/components/ui/toaster"
import SupabaseUserProvider from "@/lib/providers/supabaseUserProvider";
import AppStateProvider from "@/lib/providers/state-provider";
import { SocketProvidor } from "@/lib/providers/socket-providor";
import { SubscriptionModalProvider } from "@/lib/providers/subscription-modal-providor";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // console.log("this is the db object:", db) 

  return (
    <html lang="en" suppressHydrationWarning={true}> 
      <body className={ twMerge('bg-background', inter.className)} suppressHydrationWarning={true}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <AppStateProvider>
            <SupabaseUserProvider>
              <SocketProvidor>
                
                  {children}
                
              </SocketProvidor>
            </SupabaseUserProvider>
          </AppStateProvider>
          <Toaster />
        </ThemeProvider>
        </body>
    </html>
  );
}
